[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run typecheck && npm run build"

[deploy]
startCommand = "npm run start -w @inochi/web"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
